import type { Metadata } from "next";
import { Geist, Geist_Mono, Stack_Sans_Headline } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "./components/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const stackSansHeadline = Stack_Sans_Headline({
  subsets: ["latin"],
  variable: "--font-stack-sans-headline",
});

export const metadata: Metadata = {
  title: "The Witness Collection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${stackSansHeadline.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-stack-sans">
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
